#import "@local/templat-projektarbeit:0.1.17": *
#import "../../Zusatz/acronyms.typ": acronyms

= Conclusion

This project investigated the validity and quality of the #acr("CT") adequacy calculations produced by #acr("SECP") Global. The calculations were compared against an independent reference model derived from #acr("IEC") 61869-2, #acr("IEC") TR 61869-100 and the applicable device manuals and the generated reports were assessed for traceability, coverage and fitness for customer delivery. Three application–device cases were examined: transformer differential protection with the RET670, line differential protection with the RED670 and overcurrent protection with a REF650 requirement.

During the investigation the focus evolved from the search for isolated calculation errors towards a systematic evaluation methodology. Framed as an evaluation study within design-science research and structured as a single-case study, the work operationalised the release question through a set of research questions, a non-compensatory decision rule, a goal–question–metric measurement scheme and a three-level defect classification. This shift was motivated by the recognition that a dependable engineering result requires not only a correct final decision but also numerically correct intermediate values, faithful formulae and a traceable, current report.

The results differ markedly between the three cases. For line differential protection, #acr("SECP") applies a correctly formed criterion and agrees closely with the reference model, the only difference being a small conservative deviation attributable to the cable-resistance basis; this case is releasable subject to disclosure of that deviation. For transformer differential protection, the suitability decisions agree with the reference in every case, yet the required value is numerically incorrect: the tool counts the secondary lead resistance twice, over-estimating the requirement by a mean of roughly nine percent and by up to twenty-two percent. The deviation is conservative, so an inadequate #acr("CT") cannot be accepted, but the printed formula departs from the very device requirement the report cites and the deficiency is a tool-level defect rather than a report-level one. For overcurrent protection, the required REF650 is not selectable and only the REF630 substitute is offered on a different dimensioning basis, so the case cannot be computed with the required device and its coverage remains a blocker until equivalence is demonstrated or the device is added.

A cross-cutting finding applies to every generated report: #acr("SECP") cites #acr("IEC") 61869-1:2007, a superseded edition of the general-requirements standard, whereas the applied part-2 and part-100 references remain current. This weakens the delivered document as an auditable record and is recorded separately from the numerical findings, since the specific deficiency identified in this work stems from the lead-resistance term rather than from the outdated reference.

Methodologically, the evaluation demonstrated why numerical output must be checked rather than only final decisions. Because the transformer-differential deviation is conservative, every suitability verdict matched the reference and a decision-only check would have reported full agreement while the underlying required value was wrong. Only the comparison against an independent reference, together with the separation of the computation layer from the presentation layer, exposed the defect and identified it as both a correctness and a traceability finding with a single root cause.

Applying the non-compensatory decision rule, #acr("SECP") Global is not releasable without qualification for the planning-phase use case in its present state. It is usable now for line differential protection and its transformer-differential results are safe to rely on in the conservative direction while the defect is outstanding; unqualified release nonetheless depends on correcting the transformer-differential lead-resistance term, closing the overcurrent coverage gap and updating the superseded normative reference. Beyond these specific corrections, the project recommends that independent reference calculation and structured, repeatable validation be retained as standing practice when #acr("SECP") calculations are relied upon and that the identified findings be treated as software defects to be corrected and retested rather than as isolated observations.
