#import "@local/templat-projektarbeit:0.1.17": *
#import "../../Zusatz/acronyms.typ": acronyms

= Conclusion

This project investigated the validity and quality of current transformer (CT) calculations generated by SECP Global. The original objective was to compare SECP calculation results with independent reference calculations and to assess the quality of the generated reports using a structured validation and evaluation methodology. The project further aimed to identify discrepancies, document limitationsand derive recommendations for future application and development of the software.

During the course of the investigation, the project focus evolved from the identification of isolated calculation errors towards the development of a systematic validation methodology for CT calculation results and report quality. This shift was motivated by the observation that reliable engineering results require not only mathematically correct calculations but also sufficient transparency, consistency, traceabilityand reproducibility of the generated documentation.

The performed validation activities revealed several types of deficiencies within SECP-generated calculation reports. These included calculation inconsistencies, logical contradictions, reporting inconsistencies, formatting issuesand cases of limited traceability caused by missing intermediate validation information. The review demonstrated that individual numerical results and engineering conclusions cannot always be verified directly from the information presented in the generated reports.

A structured error classification and assessment approach was therefore identified as an important component of the overall validation process. The project established the basis for evaluating calculation correctness, report consistencyand technical traceability in a repeatable and systematic manner. In addition to supporting the identification of software defects, such an approach enables a more objective assessment of engineering report quality and facilitates future validation activities.

The results indicate that software validation in protection-engineering applications must extend beyond the verification of final adequacy decisions. Even when a final result remains unchanged, inconsistencies in intermediate calculations or report generation can reduce confidence in the engineering output and complicate independent verification. Consequently, the quality of both the calculation algorithms and the generated documentation must be considered during software assessment.

Based on the findings of this project, the continued use of independent reference calculations and structured validation procedures is recommended when assessing CT calculations generated by SECP Global. Furthermore, identified calculation and report-generation inconsistencies should be treated as validation findings and addressed through systematic software improvement and retesting activities.

In conclusion, the project demonstrated the value of a structured validation and quality assessment framework for CT calculations in SECP Global. The developed methodology provides a foundation for identifying calculation discrepancies, evaluating report qualityand supporting informed engineering decisions. As a result, the work contributes to improving the transparency, traceabilityand overall confidence in software-assisted CT calculation processes.
