#let acronyms = (
  Abt: "Abteilung",
  CO2: "Kohlenstoffdioxid",
  DIN: "Deutsches Institut für Normen",
  IBN: "Inbetriebnahme",
  IBS: "Inbetriebsetzung",
  MVA: "Mega Volt Amper",
  OS: "Oberspannungsseite",
  US: "Unterspannungsseite",
  RCD: "Residual-current device",
  SCADA: "Supervisory Control and Data Acquisition",
  SF6: "Schwefelhexafluorid",
  Trafo: "Transformator",
  UWW: "Umspannwerk Waldheim",
  VDE: "Verband der Elektrotechnik Elektronik Informationstechnik e. V",
  HSE: "Health, Safety und Environment",
  KI: "Künstliche Inteligenz",
  STATCOM: "Static Synchronous Compensator",
  PSA: "Persönliche Schutzausrüstung",
  Ω: "Ohm",
  M: "mega",
  UW: "Umspannwerk",
  GIS: "Gasisolierte Schaltanlag",
  AC: "Wechselstrom",
  DC: "Gleichstrom",
  k: "kilo",
  V: "Volt",
  m: "mili",
  A: "Ampere",
  s: "Sekunde",
  PV: "Photovoltaik",
  FACTS: "Flexible AC Transmission System",
  SVC: "Statischer Blindleistungskompensator",
)