#let acronyms = (
  Abt: "Abteilung",
  CO2: "Kohlenstoffdioxid",
  DIN: "Deutsches Institut für Normen",
  IBN: "Inbetriebnahme",
  IBS: "Inbetriebsetzung",
  MVA: "Mega Volt Amper",
  OS: "Oberspannungsseite",
  US: "Unterspannungsseite",
  RCD: "residual-current device",
  SCADA: "Supervisory Control and Data Acquisition",
  SF6: "Schwefelhexafluorid",
  Trafo: "Transformator",
  UWW: "Umspannwerk Waldheim",
  VDE: "Verband der Elektrotechnik Elektronik Informationstechnik e. V",
  HSE: "Health, Safety und Environment",
  KI: "Künstliche Inteligenz",
  STATCOM: "Static Synchronous Compensator",
)