#import "@local/templat-projektarbeit:0.1.18": *
#import "../../Zusatz/acronyms.typ": acronyms

= Theoretical Background

This chapter establishes the theoretical basis for the validation and quality assessment of current-transformer calculations in #acr("SECP") Global. It introduces the operating principles of #acrfpl("CT"), their use in transformer differential, line differential and overcurrent protection and the #acr("CT") performance parameters used in protection-oriented dimensioning.

== #acrl("CT")

A #acr("CT") is an instrument transformer whose secondary current is substantially proportional to the primary current under normal conditions, with an approximately zero phase displacement for the correct connection direction. A protective #acr("CT") is specifically intended to supply a current signal to protection and control devices. #cite(<IEC_61869_2>) In power-system use it converts a high primary current $I_p$ into a lower secondary current $I_s$. The transformation is set primarily by the turns ratio; the relevant characteristics include the rated primary and secondary currents, accuracy class, accuracy limit factor, excitation characteristic, secondary winding resistance and rated burden. #cite(<Mustajärvi_Instrument_Transformer>)

The simplified equivalent circuit contains the secondary winding resistance $R_"ct"$, the connected burden and a magnetising branch. Because part of the transformed current is required for excitation, the secondary current does not reproduce the primary perfectly, which produces a ratio error and a phase displacement. #cite(<Mustajärvi_Instrument_Transformer>), #cite(<ABB_Instrument_Transformers>) #cite(<IEC_61869_2>) distinguishes measuring cores, which need accuracy within their measuring range, from protective cores, which must retain sufficient reproduction at the much higher currents occurring during faults. #cite(<Mustajärvi_Instrument_Transformer>)

For protection, the magnetic behaviour of the core is decisive. As the secondary #acr("emf") and the associated flux rise, the core approaches saturation. An increasing share of the primary current is then used for magnetisation and the secondary current becomes distorted, which may cause failure to operate or unwanted operation, depending on the protection principle. #cite(<IEC_61869_100>), #cite(<Mustajärvi_Instrument_Transformer>) Fault performance therefore depends not on the primary current alone but also on the #acr("CT") ratio, the winding resistance, the secondary-lead impedance and the connected device burden. The burden is the impedance of the secondary circuit, including the protection device and the wiring; cable length, cross-section, material and temperature all influence the lead resistance and hence the total secondary burden. #cite(<Mustajärvi_Instrument_Transformer>), #cite(<ABB_Instrument_Transformers>)

== Protection Applications

Different protection functions process the secondary signal by different principles and therefore place different requirements on the associated #acrpl("CT"). The #acr("CT") specification must consequently be related to the protection function and not to the primary current rating alone. #cite(<IEC_61869_100>), #cite(<Mustajärvi_Instrument_Transformer>)

=== Transformer Differential Protection

Differential protection compares the currents entering and leaving a protection zone. Under normal load and external faults the vector sum of the correctly referred currents is ideally zero, whereas an internal fault produces a differential current. In transformer differential protection the compared currents are measured by #acrpl("CT") on the different sides of the power transformer. A direct comparison therefore first requires compensation for the transformer vector-group phase shift, the secondary-current magnitude difference and zero-sequence current; in numerical devices these corrections are performed in software from the entered #acr("CT") and transformer data. #cite(<RET670_Application_Manual>), #cite(<REF650_Technical_Guide>)

Even with correct compensation, several non-fault phenomena can produce an apparent differential current, for example tap-changer mismatch, differing #acr("CT") characteristics, single-side zero-sequence current, magnetising and inrush current and overexcitation. #cite(<RET670_Application_Manual>) A restrained characteristic is therefore used, in which the required operating current rises with the through-current (the highest measured transformer current serving as the bias quantity). This gives stability during through faults while retaining sensitivity. #cite(<RET670_Application_Manual>), #cite(<REF650_Technical_Guide>) The dimensioning condition is the external through fault: if the #acrpl("CT") on the two sides saturate unequally, their secondary currents diverge and appear as a false differential current, which the higher-restraint sections of the characteristic must accommodate. #cite(<IEC_61869_100>) #cite(<IEC_61869_100>) recommends core dimensioning based on the relevant fault occurrences and identifies anti-remanence classes such as 5PR, TPY, TPZ and PXR as applicable, with the specific requirement to be taken from the device documentation.

=== Line Differential Protection

Line differential protection applies the same principle to a protected line. Because the line changes neither voltage level nor phase, no vector-group compensation is required and the currents at both ends refer to the same primary quantity. #cite(<RED670_Application_Manual>) The #acrpl("CT") are installed at the geographically separated line ends, so the measured currents are exchanged between the line-end #acrpl("IED") over a communication channel before the differential quantity is formed. Differing #acr("CT") ratios and characteristics together with the line charging current produce a small standing differential current that the restrained characteristic must tolerate without operating. #cite(<RED670_Application_Manual>), #cite(<IEC_61869_100>) As for every differential principle, the external through fault is the dimensioning case. The RED670 states its requirement as a rated equivalent limiting secondary #acr("emf") $E_"al"$ that the selected #acr("CT") must satisfy through $E_"al" >= E_"al,req"$. The required value is derived from the relevant fault current, the #acr("CT") ratio, the secondary-loop resistance and a device-specific factor, but without the additional through-fault multiplier of the two-transformer arrangement. This is the quantity against which #acr("SECP") is compared for the line-differential case. #cite(<RED670_Application_Manual>), #cite(<IEC_61869_100>)

=== Overcurrent Protection

Overcurrent protection operates when the measured current exceeds a pickup value, using instantaneous, definite-time or inverse-time characteristics. #cite(<Mustajärvi_Instrument_Transformer>) Because the decision is based directly on the current magnitude, the #acr("CT") ratio error is particularly relevant; directional functions additionally depend on the phase displacement. #cite(<IEC_61869_2>) represents the combination of both as the composite error. The #acr("CT") requirement depends on the characteristic: #cite(<IEC_61869_100>) gives separate recommendations for non-directional and directional functions, requires the accuracy limit factor to exceed the maximum current setting for definite stages and an #acr("ALF") above 20 for inverse stages and identifies class 10P for non-directional and 10P or 5P for directional protection. The overcurrent application must therefore be defined before #acr("CT") adequacy can be assessed, since the maximum close-in fault current, primary pickup current, #acr("CT") ratio, winding resistance, device burden and lead resistance enter the corresponding required-#acr("emf") condition differently for each case. #cite(<Mustajärvi_Instrument_Transformer>)

== #acr("CT") Performance Parameters

The rated primary and secondary currents $I_"pr"$ and $I_"sr"$ define the rated transformation ratio used to refer the primary current to the secondary side. #cite(<IEC_61869_2>) The secondary winding resistance $R_"ct"$ contributes to the internally induced voltage required to drive the secondary current, so a larger $R_"ct"$ raises the required secondary #acr("emf"). The burden is the impedance connected to the secondary circuit, comprising the device input and the leads. Because it determines part of the required voltage, accuracy and saturation must be assessed at the applicable burden. #cite(<IEC_61869_2>), #cite(<Mustajärvi_Instrument_Transformer>) The rated output $S_n$ is expressed in volt-amperes for measuring #acrpl("CT") and classes P and PR and as a rated resistive burden in ohms for classes TPX, TPY and TPZ. #cite(<IEC_61869_2>)

The accuracy class defines the applicable error limits. For classes P and PR it bounds ratio error, phase displacement and composite error, the last of which cannot be smaller than the vector combination of the first two. #cite(<IEC_61869_2>) The accuracy limit factor $K_"ALF"$, commonly abbreviated #acr("ALF"), is the ratio of the rated accuracy-limit primary current $I_"ALF"$ to the rated primary current:

$ K_"ALF" = I_"ALF" / I_"pr" $ <eq-kalf>

equivalently $I_"ALF" = K_"ALF" I_"pr"$, where $I_"ALF"$ is the primary current up to which the composite-error requirement is met. #cite(<IEC_61869_2>) For classes PX and PXR the requirement is expressed through the knee-point #acr("emf"), related to the dimensioning factor $K_x$, the winding resistance, the rated burden resistance and the rated secondary current:

$ E_k = K_x (R_"ct" + R_b) I_"sr" $ <eq-ek>

Saturation is the region in which the core can no longer reproduce increasing primary current proportionally; fault-current asymmetry and its decaying d.c. component raise the flux beyond that of the symmetrical component alone. #cite(<IEC_61869_100>) Remanence, the flux remaining after excitation is removed, reduces the remaining flux margin and can advance saturation in a subsequent fault. Classes PR, PXR and TPY include a remanence limit, whereas P, PX and TPX do not; TPZ is specified through a secondary time constant. #cite(<IEC_61869_2>), #cite(<IEC_61869_100>) The classes thus represent different specification methods: P/PR through the composite error, PX/PXR through the excitation characteristic and TPX/TPY/TPZ through the transient error. Class selection follows the protection principle, the expected fault conditions, the burden and the device requirement. #cite(<IEC_61869_100>), #cite(<IEC_61869_2>)

== Transient Dimensioning of Protective #acrpl("CT")

The parameters above describe symmetrical steady-state behaviour. A real short-circuit current contains a decaying d.c. component whose magnitude depends on the fault-inception instant and the primary time constant. It adds a unidirectional contribution to the secondary flux and can drive the core into saturation well below the value implied by the a.c. component alone. #cite(<IEC_61869_2>), #cite(<IEC_61869_100>) #cite(<IEC_61869_2>) addresses this through a set of dimensioning quantities: the rated symmetrical short-circuit current factor, the transient factor, the transient dimensioning factor and the rated equivalent limiting secondary #acr("emf"). Together they express the required core performance as a single voltage.

The rated symmetrical short-circuit current factor $K_"ssc" = I_"psc" \/ I_"pr"$ is the ratio of the rated primary short-circuit current to the rated primary current. It characterises only the symmetrical component and is the transient counterpart of the accuracy limit factor. #cite(<IEC_61869_2>) The transient factor $K_"tf"$ is time-dependent, being the ratio of the secondary linked flux at a given duty-cycle instant to the peak of its a.c. component. The transient dimensioning factor $K_"td"$, in contrast, is the definitive rating-plate value, taken from the device-manufacturer requirement (from relay stability type tests) or from a worst-case evaluation of the $K_"tf"$ curves. #cite(<IEC_61869_2>), #cite(<IEC_61869_99>) #cite(<IEC_61869_100>) stresses that $K_"td"$ should rest on relay tests with saturated #acr("CT") models rather than on formulae alone. It therefore depends on both the protection function and the specific device, which becomes relevant wherever a tool assigns a fixed factor to a whole application category.

The rated equivalent limiting secondary #acr("emf") $E_"al"$ is the r.m.s. secondary-circuit #acr("emf") at rated frequency needed to meet the specified duty cycle:

$ E_"al" = K_"ssc" dot K_"td" dot (R_"ct" + R_b) dot I_"sr" $ <eq-eal>

where $R_b$ is the rated resistive burden and $R_"ct" + R_b$ the secondary loop resistance $R_s$. #cite(<IEC_61869_2>) This is the voltage form in which modern numerical devices state their #acr("CT") requirement and in which the adequacy assessment is ultimately performed. #cite(<Mustajärvi_Instrument_Transformer>)

#cite(<IEC_61869_100>) presents the three approaches as an #acr("emf") at limiting conditions. For classes P and PR:

$ E_"ALF" = K_"ALF" dot I_"sr" dot (R_"ct" + Z_b) $ <eq-ealf>

with $E_k$ from @eq-ek for classes PX and PXR and $E_"al"$ from @eq-eal for classes TPX, TPY and TPZ. The factors $K_"ALF"$, $K_x$ and the product $K_"ssc" dot K_"td"$ are each the ratio between the #acr("emf") at limiting conditions and that at rated burden and current. They are therefore comparable through the approximate conversions $E_"ALF" approx E_"al"$ and $E_k approx E_"al" \/ F$, with $F$ between 1.2 and 1.3 for non-gapped and about 1.1 for gapped cores. #cite(<IEC_61869_100>) These are approximations, not equalities: #cite(<Mustajärvi_Instrument_Transformer>) notes that there is no general relation between the knee-point #acr("emf") and $E_"al"$, the knee-point value being typically about 80 % of $E_"al"$, so any class conversion must be justified per case.

Where the operational burden $R'_b$ differs from the rated burden, an operational accuracy limit factor $K'_"ALF" = K_"ALF" (R_"ct" + R_b) \/ (R_"ct" + R'_b)$ follows. #cite(<IEC_61869_100>) notes two limitations of this conversion: it requires the winding resistance, which is not a specified quantity for classes P, PR, TPX, TPY and TPZ and it originates from an earlier generation of high-burden electromechanical devices. The report states that it is not in line with #acr("IEC") 61869-2 and does not recommend it for new installations, because cores with a high rated burden and low accuracy limit factor may fail their class at very low operational burdens. This point is directly relevant here, since a modern numerical relay's operational burden is typically well below the rated burden of an older core.

An adequacy assessment compares a required value derived from the application with a rated value derived from the #acr("CT") data. The required equivalent limiting secondary #acr("emf"), $E_"al,req"$, follows from the protection function, the relevant fault current, the secondary loop resistance and the applicable dimensioning factor; the #acr("CT") is adequate when

$ E_"al" >= E_"al,req" $ <eq-adequacy>

For class P or PR the comparison uses the secondary limiting #acr("emf") ($approx E_"al"$); for class PX or PXR it uses the knee-point #acr("emf") (lower by $F$), so the same physical core can yield different numerical margins depending on the specification route. #cite(<IEC_61869_100>), #cite(<Mustajärvi_Instrument_Transformer>) Because the required value depends on the protection function, the applicable dimensioning factor and the assumed worst-case fault, these three inputs must be identified explicitly before any comparison is meaningful. They form the basis of the validation developed in the following chapters.
