#import "@local/templat-projektarbeit:0.1.16": *
#import "../../Zusatz/acronyms.typ": acronyms

= Introduction

== Background and Motivation
#acrf("SECP") Global provides calculation functions for assessing current transformers used in protection and metering applications. The correctness, consistency and traceability of these calculations are important because their results support the specification of #acrpl("CT") for electrical power system applications.

The project initially assumed that #acr("SECP") Global was largely ready for practical use and required primarily validation and supporting documentation. However, the investigation revealed further calculation and reporting inconsistencies. The project therefore focuses on the systematic verification of #acr("CT") calculations and the structured assessment of calculation and report quality.

== Problem Statement
Selected #acr("CT") calculations generated by #acr("SECP") Global require systematic comparison with independent reference calculations. This assessment must consider not only final numerical results but also formulas, intermediate values, logical evaluations and the traceability of the generated reports.

Previous project reviews identified numerical discrepancies, logical inconsistencies, unclear result evaluations and reporting deficiencies. A structured methodology is therefore required to determine whether the investigated calculations are correct, internally consistent, technically plausible and sufficiently documented.

== Objectives of this Project
The primary objective is to validate selected #acr("CT") calculations in #acr("SECP") Global through independent reference calculations and to assess the quality of the corresponding calculation reports.
The project pursues the following objectives:

1. Review the relevant theoretical background and protection applications.
2. Select important #acr("CT") calculation cases.
3. Compare #acr("SECP") Global results with independent reference calculations.
4. Assess calculation accuracy, consistency and engineering plausibility.
5. Classify formula, numerical, logical, documentation and traceability deficiencies.
6. Evaluate the quality of the generated calculation reports.
7. Document limitations and potential improvement opportunities.

The project also aims to establish a repeatable methodology for reviewing calculations, intermediate values, logical evaluations and report content.

== Scope and Limitations

The project is limited to #acr("CT") calculations in #acr("SECP") Global, with particular attention to transformer differential protection and overcurrent protection. The investigation covers selected representative cases rather than every #acr("CT") application and parameter combination supported by #acr("SECP") Global.

The validation includes comparisons with independent reference calculations and an assessment of formulas, intermediate results, calculation logic, documentation quality and traceability. Formal software certification or certified approval of protection-engineering designs is not part of the project. The investigation is further limited by the availability of information concerning the formulas, assumptions, calculation methods and engineering requirements implemented in #acr("SECP") Global.
