#import "@local/templat-projektarbeit:0.1.18": *
#import "../../Zusatz/acronyms.typ": acronyms

= The #acr("SECP") Global #acr("CT") Calculation Process

This chapter describes the current #acr("SECP") Global process for #acr("CT") calculations: the overall application, the #acr("CT") calculation workflow, the protection functions covered and the generation and content of the calculation reports. The description is limited to the functionality documented in the #acr("SECP") user manual and the structure observed in the available calculation reports.

== Overview of #acr("SECP") Global

#acr("SECP") is an offline application combining several substation-engineering calculation modules, including conductor design and loading, lightning protection, #acr("CT") and #acr("VT") adequacy checks, battery and charger sizing, auxiliary-transformer sizing and neutral-grounding-resistor sizing, with support for both SI and Imperial units. It is organised around project files (extension `.secp.proj`) that can be created, opened, copied, imported or exported. Data relevant to several calculations can be entered once and reused, which reduces the engineering effort. #acr("CT") calculations form part of the combined #acr("CT") and #acr("VT") adequacy-check module, which assesses the suitability of instrument transformers for selected protection or metering applications.

Within this module, #acr("CT") data are organised in a hierarchy of scenario, bay, #acr("CT") core, application and #acr("CT") tap: up to five scenarios (representing voltage levels) per substation, up to 25 bays per scenario, up to six cores per protection #acr("CT") (twelve for iteration and cross-verification) and up to three applications per core. The generated reports reproduce this hierarchy, presenting project and document information followed by scenario, bay, core, application, input data, calculation steps and the final adequacy result.

== #acr("CT") Calculation Workflow

A calculation begins with a new or reused #acr("SECP") project, to which general project and document information is assigned (identifiers, substation and customer data, voltage level, revision and the responsible persons). Each scenario carries the general system data, namely switchyard type, nominal system voltage, frequency and maximum conductor temperature, and is subdivided by bay and #acr("CT") core. Each core is assigned an application that determines the application-specific input fields and the subsequent calculation sequence.

The core and #acr("CT") inputs comprise the core and cable data (conductor type, cross-section, direct-current resistance at 20 °C, cable length and runs, relay manufacturer, model and burden) and the per-tap #acr("CT") data (primary current, nominal secondary current, internal resistance, rated output, accuracy limit factor and upper limiting excitation current). Application-specific parameters are added on top: for overcurrent, the directional, non-directional, inverse-time and breaker-failure selections and a maximum close-in fault current; for transformer differential, quantities such as the primary source time constant, transformer rating and impedance, busbar arrangement and system type.

#acr("SECP") then processes the data in successive stages: lead resistance at the specified conductor temperature, relay parameters, the actual #acr("CT") burden, application-specific fault calculations and finally the required and proposed #acr("CT") performance quantities. The required value is compared with the proposed value to derive a per-tap adequacy result. The precise equations depend on the selected function and #acr("CT") class. In the overcurrent report, for example, #acr("SECP") reports lead and relay resistance, the actual #acr("CT") burden, a required knee-point voltage and a proposed value from the #acr("CT") data, closing with a tap summary. The transformer-differential report follows the same structure but adds transformer and fault quantities (rated primary current, through-fault power, application-specific currents) that feed the required secondary limiting electromotive force before the per-tap comparison.

== Protection Functions Covered by #acr("SECP")

The module supports #acr("CT") sizing for seven application categories: overcurrent, line differential, transformer differential, high- or low-impedance busbar, distance, high- or low-impedance transformer restricted-earth-fault and metering protection, with up to three applications per core. The supplied reports provide direct examples for overcurrent and transformer differential protection. The REF650 required for the overcurrent planning case is not selectable; this gap is examined in the assessment chapters.

== Generation of Calculation Reports

#acr("SECP") generates standardised summary and detailed reports as editable Microsoft Word files. A detailed report contains the input data, calculation steps, formulae and results; a summary report contains inputs and final results only. Before generation the user selects the scenario and element, the number of decimal digits and whether unselected elements are summarised. The detailed report follows a consistent structure: cover page and table of contents, project and document information, the referenced standards and nomenclature, then the calculation organised by scenario, bay, core, application and tap. Each application closes with a summary that consolidates the principal #acr("CT") data and results (currents, class, #acr("ALF"), proposed and calculated knee-point voltages, burden and adequacy).

It is important to distinguish report generation from report correctness. A detailed report presents each formula, its substituted values and the resulting verdict and the inline verdicts and tap summaries in the available report are mutually consistent. This internal consistency does not, however, establish that the displayed formulae match the applicable device requirement or that the numerical values are correct. Whether the calculations are faithful to the governing standard and device documentation is examined in the assessment chapters rather than assumed from a complete, self-consistent report.
