#import "@local/templat-projektarbeit:0.1.17": *
#import "../../Zusatz/acronyms.typ": acronyms

= The #acr("SECP") Global #acr("CT") Calculation Process

This chapter describes the current process used by #acr("SECP") Global to perform current-transformer calculations. It introduces the overall application, explains the structure and sequence of the #acr("CT") calculation workflow, identifies the protection functions supported by the #acr("CT") calculation module and outlines the generation and content of calculation reports. The description is limited to the functionality documented in the provided #acr("SECP") user manual and the structure observed in the available calculation reports.

== Overview of #acr("SECP") Global

#acr("SECP") is described as an offline application that combines several calculation modules used in substation engineering. The available modules include conductor design and loading calculations, lightning protection calculations, #acr("CT") and #acr("VT") adequacy checks, battery and charger sizing, auxiliary transformer sizing and neutral grounding resistor sizing. The application supports calculations in both SI and Imperial units. It also permits existing project data to be reused when new projects are created.

The application is organised around project files. A new project can be created, an existing project can be opened or copied and project files can be imported or exported. Exported project files use the .secp.proj file extension. The project toolbar provides access to the principal functions required for working with a project, including project creation, project management, saving, importing, exporting, unit conversion, calculation execution and the generation of detailed and summary reports.

The use of a common project structure allows information that is relevant to several calculations to be entered once and reused. The user manual identifies the reuse of project data and calculations as a means of reducing engineering effort. Project files may also be stored in a server location and restored if required.

Within #acr("SECP"), #acr("CT") calculations form part of the combined #acr("CT") and #acr("VT") adequacy-check module. This module is intended to assess the suitability of instrument transformers for selected protection or metering applications. For #acr("CT") calculations, the application associates project-level data with a hierarchical arrangement of scenarios, bays, #acr("CT") cores, applications and #acr("CT") taps. The generated reports reproduce this hierarchy by first presenting project and document information, followed by the applicable scenario, bay, core, application, input data, calculation steps and final adequacy result.

== #acr("CT") Calculation Workflow

The #acr("CT") calculation process begins with the creation or opening of a #acr("SECP") project. The user can create a new project file or reuse an existing project by copying it from the project-management view. #acr("SECP") also supports the import of an existing .secp.proj file. General project and document information can subsequently be assigned to the project. These data may include the project identifier, project name, substation name, customer name, country, voltage level, document revision, document number and the persons responsible for preparation, review and approval.

The project is divided into scenarios representing voltage levels. The #acr("CT") and #acr("VT") adequacy-check module permits up to five scenarios within one substation project and up to 25 bays within each scenario. Each bay contains #acr("CT") or #acr("VT") data. A protection #acr("CT") may contain up to six cores, while iteration calculations may be performed for up to twelve cores for trial and cross-verification purposes. The module also permits up to three applications to be assigned to one #acr("CT") core.

For each scenario, the user enters the applicable general system data. The scenario section can contain the switchyard type, nominal system voltage, system frequency and maximum conductor temperature. The reports then subdivide the calculation according to the selected bay and #acr("CT") core. Each core is assigned an application that determines the application-specific input fields and the subsequent calculation sequence.

The core data includes the core designation, selected application, accuracy class, number of primary #acr("CT") taps, relay manufacturer, relay model and relay burden. The cable circuit is represented through parameters such as conductor type, cross-sectional area, direct-current resistance at 20 °C, cable length, number of cable runs and where applicable, loop-cable connections. The #acr("CT") input data are entered separately for each tap and include the primary current, nominal secondary current, internal #acr("CT") resistance, rated output, accuracy limit factor and upper limiting excitation current.

Application-specific relay and system parameters are entered in addition to the common core and #acr("CT") data. For overcurrent protection, the selections for directional overcurrent, non-directional overcurrent, non-directional inverse-time overcurrent and breaker-failure protection, together with a maximum close-in fault current. For transformer differential protection, the reports contain parameters such as the primary source time constant, transformer rating, transformer impedance at the principal tap, the selected busbar arrangement, the system type and application-specific current quantities. The exact set of required fields therefore depends on the protection function selected for the core.

The detailed reports indicate that #acr("SECP") processes the entered data in several successive calculation stages. These can include the determination of cable lead resistance at the specified conductor temperature, the calculation of relay parameters, the determination of the actual #acr("CT") burden, application-specific fault calculations and the calculation of required and proposed #acr("CT") performance quantities. The resulting values are compared to derive an adequacy assessment for each #acr("CT") tap. The precise equations and intermediate quantities depend on the selected protection function and #acr("CT") class.

For example, the available overcurrent-protection report first presents the relay input data, core data, loop-cable data and #acr("CT") tap data. It then reports the calculation of lead resistance, relay resistance, actual #acr("CT") burden, required knee-point voltage and a proposed value derived from the entered #acr("CT") parameters. The final section provides a tap-specific summary containing the #acr("CT") ratio, accuracy class, accuracy limit factor, proposed and calculated knee-point voltages, burden values and adequacy results.

The transformer differential protection reports follow a comparable structure but include additional transformer and fault-related quantities. The calculation report determines quantities such as the rated primary current of the transformer, the transformer through-fault power and application-specific current values. These quantities are subsequently used in the calculation of the required secondary limiting electromotive force or knee-point voltage. The requirement obtained from the application-specific calculation is compared with the value derived from the proposed #acr("CT") data, after which an adequacy result is assigned to the individual tap.

== Protection Functions Covered by #acr("SECP")

The #acr("CT") and #acr("VT") adequacy-check module supports #acr("CT") sizing for seven application categories: overcurrent protection, line differential protection, transformer differential protection, high- or low-impedance busbar protection, distance protection, high- or low-impedance transformer restricted-earth-fault protection and metering. The module also permits multiple applications to be assigned to a single #acr("CT") core, with a documented maximum of three applications per core.

The supplied calculation reports provide direct examples for overcurrent protection and transformer differential protection. The overcurrent-protection example contains function-specific selections for directional, non-directional, inverse-time and breaker-failure elements. Its calculation output includes both a #acr("CT") burden assessment and a comparison of required and proposed #acr("CT") performance quantities. The transformer differential protection examples include transformer data and fault calculations before the required and proposed secondary limiting electromotive-force values are compared.

== Generation of Calculation Reports

#acr("SECP") provides standardised generation of both summary and detailed reports. The reports are generated as editable Microsoft Word files. A detailed report contains the input data, calculation steps and procedures, formulae and output results. A summary report contains the input data and final output results without reproducing the complete calculation sequence. Both report types can be accessed through the Reports menu or the corresponding shortcut in the application interface.

Before generating a report, the report configuration allows the user to select the relevant scenario and calculation element, define the number of decimal digits and specify whether summary results for unselected elements within a selected scenario are required. The configuration is saved before the report is generated. When a summary report is requested, #acr("SECP") opens the generated Word file in a new window. During detailed-report generation, the application updates the Microsoft Word table of contents before opening the completed report.

The available detailed calculation reports follow a consistent structure. They begin with a cover page and table of contents, followed by project and document information. The reports then identify the referenced standards and define the nomenclature used for symbols and units. The calculation content is organised by scenario, bay, #acr("CT") core, application and tap. For each application, the reports document the input data, intermediate calculations, formulae, comparison criteria and a final application summary.

The application summary consolidates the principal #acr("CT") data and results for each tap. Depending on the selected function, this may include the primary and secondary currents, #acr("CT") accuracy class, accuracy limit factor, proposed and calculated knee-point voltages, #acr("CT") burden and the resulting adequacy classifications. This structure provides a compact representation of the final outcome while retaining a connection to the more extensive calculation sequence contained in the preceding pages of the detailed report.

The supplied reports also reveal a potential distinction between report generation and report correctness. In one transformer differential protection example, the comparison states that the proposed knee-point voltage is lower than the required value, while the accompanying sentence states that the #acr("CT") tap is adequate. The application summary for the same tap identifies the result as not adequate. This is an explicit internal inconsistency within the generated report and demonstrates that the presence of detailed calculations and an automatically generated summary does not, by itself, establish the correctness or consistency of the reported assessment.

Accordingly, the existing #acr("SECP") process can be characterised as a project-based calculation workflow in which common system data, protection-specific parameters, cable data and #acr("CT") characteristics are entered within a hierarchical project structure. #acr("SECP") executes the selected calculations and generates editable reports containing both detailed calculation paths and consolidated results.
