#import "@local/templat-projektarbeit:0.1.18": *
#import "../../Zusatz/acronyms.typ": acronyms
#set text(hyphenate: false)
#set par(spacing: 2em)


This thesis evaluates the reliability and quality of #acr("CT") adequacy calculations generated by #acrs("SECP") Global for planning-phase engineering applications. The investigation focuses on transformer differential, line differential, and overcurrent protection.

The assessment combines numerical verification against an independent Excel-based reference calculation with a structured evaluation of traceability, functional coverage, and report quality. The reference calculation is derived from the #acr("IEC") 61869 series and the application manuals of the investigated protection devices. Four research questions were used to assess numerical correctness, traceability of reported calculations, coverage of required applications, and suitability of the generated reports for customer delivery.

The results show that line differential protection calculations produced by #acrs("SECP") closely match the reference calculation and lead to identical suitability decisions. Transformer differential protection contains a systematic deviation caused by the double consideration of the secondary lead resistance, resulting in conservative but numerically incorrect values. In addition, the required REF650 overcurrent application is not available in #acrs("SECP"), preventing a complete assessment of this use case. Significant report-quality issues were also identified, including traceability inconsistencies, outdated standard references, and formatting deficiencies.

Overall, the investigated version of #acrs("SECP") Global cannot currently be recommended for unrestricted customer delivery of #acr("CT") calculation reports. Improvements to both the calculation implementation and the report generation process are required before release can be justified.