#import "@local/templat-projektarbeit:0.1.18": *
#import "../../Zusatz/acronyms.typ": acronyms

= Introduction

== Background and Motivation
#acrf("SECP") Global provides calculation functions for assessing current transformers used in protection and metering applications. The correctness, consistency and traceability of these calculations matter because their results support the specification of #acrpl("CT") for electrical power-system applications.

The project initially assumed that #acr("SECP") Global was largely ready for practical use and required primarily validation and supporting documentation. The investigation, however, revealed further calculation and reporting inconsistencies, so the work focuses on the systematic verification of #acr("CT") calculations and the structured assessment of calculation and report quality.

== Problem Statement
Selected #acr("CT") calculations generated by #acr("SECP") Global require systematic comparison with independent reference calculations, considering not only final numerical results but also formulae, intermediate values, logical evaluations and the traceability of the generated reports. Previous project reviews identified numerical discrepancies, logical inconsistencies, unclear result evaluations and reporting deficiencies; a structured methodology is therefore required to determine whether the investigated calculations are correct, internally consistent, technically plausible and sufficiently documented.

== Objectives of this Project
The primary objective is to validate selected #acr("CT") calculations in #acr("SECP") Global through independent reference calculations and to assess the quality of the corresponding calculation reports. Specifically, the project reviews the relevant theoretical background and protection applications; selects representative #acr("CT") calculation cases; compares #acr("SECP") results with independent reference calculations; assesses calculation accuracy, consistency and engineering plausibility; classifies formula, numerical, logical, documentation and traceability deficiencies; evaluates the quality of the generated reports; and documents limitations and improvement opportunities. In doing so it establishes a repeatable methodology for reviewing calculations, intermediate values, logical evaluations and report content.

== Scope and Limitations

The project is limited to #acr("CT") calculations in #acr("SECP") Global, with particular attention to transformer differential, line differential and overcurrent protection, and covers selected representative cases rather than every #acr("CT") application and parameter combination supported by #acr("SECP") Global. It includes comparisons with independent reference calculations and an assessment of formulae, intermediate results, calculation logic, documentation quality and traceability. Formal software certification or certified approval of protection-engineering designs is not part of the project, and the investigation is further limited by the availability of information on the formulae, assumptions, calculation methods and engineering requirements implemented in #acr("SECP") Global.
