#import "@local/templat-projektarbeit:0.1.18": *
#import "../../Zusatz/acronyms.typ": acronyms
#set text(hyphenate: false)

= Introduction

== Background and Motivation
#acrf("SECP") Global provides calculation functions for assessing #acrpl("CT") used in protection and metering applications. The correctness, consistency and traceability of these calculations matter because their results support the specification of #acrpl("CT") for electrical power-system applications.

The project initially assumed that #acr("SECP") Global was largely ready for practical use and required primarily validation and supporting documentation. The investigation, however, revealed further calculation and reporting inconsistencies, so the work focuses on the systematic verification of #acr("CT") calculations and the structured assessment of calculation and report quality.

== Problem Statement
Selected #acr("CT") calculations generated by #acr("SECP") Global require systematic comparison with independent reference calculations, considering not only final numerical results but also formulae, intermediate values, logical evaluations and the traceability of the generated reports. Previous project reviews identified numerical discrepancies, logical inconsistencies, unclear result evaluations and reporting deficiencies. A structured methodology is therefore required to determine whether the investigated calculations are correct, internally consistent, technically plausible and sufficiently documented.

== Objectives of this Project
The primary objective is to validate selected #acr("CT") calculations in #acr("SECP") Global and to assess the quality of the corresponding calculation reports. For this purpose, the results of #acr("SECP") are compared with independent reference calculations.

The work proceeds in several steps. First, the relevant theoretical background and protection applications are reviewed and representative #acr("CT") calculation cases are selected. The #acr("SECP") results are then compared with the reference calculations and checked for accuracy, consistency and engineering plausibility. Deficiencies found in the formulae, numerical values, calculation logic, documentation or traceability are classified and the quality of the generated reports is evaluated. Finally, the remaining limitations and possible improvements are documented. The result is a repeatable procedure for reviewing calculations, intermediate values, logical evaluations and report content.

== Scope and Limitations

The project is limited to #acr("CT") calculations in #acr("SECP") Global, with particular attention to transformer differential, line differential and overcurrent protection and covers selected representative cases rather than every #acr("CT") application and parameter combination supported by #acr("SECP") Global. It includes comparisons with independent reference calculations and an assessment of formulae, intermediate results, calculation logic, documentation quality and traceability. Formal software certification or certified approval of protection-engineering designs is not part of the project and the investigation is further limited by the availability of information on the formulae, assumptions, calculation methods and engineering requirements implemented in #acr("SECP") Global.
