#import "@local/templat-projektarbeit:0.1.6": *
#import "../../Zusatz/acronyms.typ": acronyms

= Transformation im Engineering
Der Übergang von 2D zu 3D war ein Paradigmenwechsel: Statt flacher Zeichnungen entstehen räumliche Modelle, die Kollisionen frühzeitig erkennen lassen und die Kommunikation zwischen Disziplinen verbessern. #acr("BIM") erweitert diesen Ansatz, indem es nicht nur Geometrie, sondern auch semantische Informationen integriert.
Der digitale Zwilling geht noch einen Schritt weiter: Er bildet das reale Objekt virtuell ab und verknüpft es mit Echtzeitdaten. So können Betriebszustände überwacht, Wartungen geplant und Prozesse optimiert werden. In der Energietechnik ermöglicht dies beispielsweise die Simulation von Lastflüssen oder die vorausschauende Instandhaltung von Netzen.

== Von 2D-#acr("CAD") zu 3D-Modellierung

Die Entwicklung des technischen Designs hat in den vergangenen Jahrzehnten einen tiefgreifenden Wandel erfahren. Während klassische Konstruktion lange Zeit fast ausschließlich anhand zweidimensionaler Zeichnungen erfolgte, setzt die Industrie zunehmend auf durchgängige digitale 3D‑Modelle. Der Übergang von 2D‑#acrs("CAD") zu 3D‑Modelling stellt jedoch weit mehr dar als eine rein grafische Modernisierung. Er ist ein zentraler Bestandteil der umfassenden Digitalisierung des Engineering‑Prozesses und bildet die Grundlage für effiziente Planung, verlässliche Datenstrukturen sowie moderne Methoden wie #acrs("BIM").
Die Digitalisierung gilt mittlerweile als ein entscheidender Motor für Produktivität, Qualität und Nachhaltigkeit im Engineering, wie in #cite(<eubimtg_handbuch_nodate>) betont wird.


=== Vorteile und Möglichkeiten
Die Transformation vom 2D‑#acrs("CAD")‑Design hin zum 3D‑Modeling eröffnet im Engineering eine vollkommen neue Qualität der technischen Darstellung, Analyse und Zusammenarbeit. Während 2D Zeichnungen lediglich abstrahierte Projektionen eines Objekts liefern, ermöglichen 3D Modelle ein vollständiges und räumliches Abbild des realen Bauteils oder Systems, was ein deutlich besseres Verständnis komplexer Zusammenhänge schafft. Digitale Modelle führen zu einer grundlegenden Verbesserung der Informationsqualität und des Verständnisses innerhalb von Projekten. Durch die Modellorientierung entstehen konsistentere Datenstrukturen, welche die Grundlage für eine effizientere Kommunikation und eine deutliche Qualitätssteigerung in der Planung bieten. Ein weiterer Vorteil liegt in der systematischen Erkennung von Konflikten und Unstimmigkeiten: Kollisionsprüfungen, automatische Abgleiche von Toleranzen und modellbasierte Prüfmechanismen identifizieren Probleme bereits in frühen Entwicklungsphasen, wie in #cite(<golinski_bim-magazin_2025>) beschrieben wird, wo modellbasierte Prüfungen und digitale Koordination als zentrale Effizienztreiber dargestellt werden. Zudem ermöglicht das 3D‑Modeling eine hohe Datenkonsistenz, da alle Informationen zentral gepflegt werden und redundante Datenverarbeitung entfällt. Aus einem einzigen digitalen Modell lassen sich automatisiert Stücklisten, Schnittansichten, Mengenermittlungen und technische Dokumentationen ableiten. Darüber hinaus bildet das Modell die Grundlage für Simulationen wie Strukturmechanik, Strömungsanalysen oder Schattenstudien, die wiederum Entscheidungen in frühen Phasen maßgeblich verbessern. Ergänzend erlaubt die Integration digitaler Zwillinge eine Nutzung des Modells über den gesamten Lebenszyklus hinweg, da es für Betrieb, Wartung und Monitoring genutzt werden kann. Dies hebt #cite(<eubimtg_handbuch_nodate>) als entscheidenden Schritt zu ganzheitlichen digitalen Prozessen hervorhebt. Schließlich verbessert die Nutzung gemeinsamer Datenumgebungen die Zusammenarbeit verschiedener Disziplinen erheblich, da alle Beteiligten im gleichen digitalen Raum arbeiten und jederzeit auf aktuelle und geprüfte Daten zugreifen können.

=== Auswirkungen auf den Designprozess
Der Übergang vom 2D‑Zeichnen zum 3D‑Modelling verändert den gesamten Designprozess grundlegend und führt zu einer strukturell neuen Herangehensweise in der technischen Planung. Früher stellten einzelne Zeichnungen das primäre Arbeitsmittel dar, während heute das digitale Modell die zentrale Informationsquelle bildet. Dieser Wandel bewirkt, dass zahlreiche Entscheidungen früher im Verlauf des Projekts getroffen werden müssen, da das Modell bereits in initialen Phasen einen hohen Detaillierungsgrad aufweist. #cite(<golinski_bim-magazin_2025>) beschreibt diese Veränderung als eine Verschiebung des Planungsaufwands in frühere Projektphasen, wodurch der Planungsprozess zwar anspruchsvoller wird, jedoch gleichzeitig an Qualität und Transparenz gewinnt. Gleichzeitig erfordert die modellbasierte Arbeitsweise eine klare Strukturierung und Standardisierung der Daten. Offene Austauschformate wie #acr("IFC") #cite(<iso_iso_2024>) stellen sicher, dass Modelle unterschiedlicher Softwareumgebungen interoperabel bleiben. Ein Aspekt, der im #cite(<eubimtg_handbuch_nodate>) als unverzichtbar für eine europaweit konsistente digitale Planung hervorgehoben wird. Da ein 3D‑Modell erheblich mehr Daten enthält als eine 2D‑Zeichnung, müssen Informationsanforderungen eindeutig definiert sein, damit sämtliche Gewerke konsistent arbeiten können. Dies wirkt sich direkt auf die interdisziplinäre Zusammenarbeit aus, die wesentlich enger und prozessintegrierter erfolgt. Der Designprozess wird zunehmend kollaborativ, da alle Beteiligten in einer gemeinsamen Datenumgebung arbeiten und das Modell als verbindliche Informationsquelle dient. Darüber hinaus begleiten Modelle nicht mehr nur die Planung, sondern zunehmend auch Genehmigungsverfahren, Bauabläufe und den späteren Betrieb. Die Kommunikation im Modell erleichtert die Vermittlung komplexer Sachverhalte, steigert die Nachvollziehbarkeit und reduziert die Fehleranfälligkeit herkömmlicher planbasierter Prozesse. Simulationen und automatisierte Prüfmechanismen machen den Designprozess iterativer und data‑driven, da Entscheidungen unmittelbar aus belastbaren digitalen Analysen abgeleitet werden können. Insgesamt entsteht durch die Transformation ein durchgängiger, modellbasierter Workflow, in dem Planung, Koordination, Auswertung und Dokumentation eng verzahnt sind und der Entwicklungsprozess effizienter, sicherer und transparenter gestaltet wird. 

== Einführuing in #acr("BIM")

#acr("BIM") beschreibt eine grundlegende Weiterentwicklung der digitalen Planung, die weit über die reine Modellierung hinausgeht. Während klassische #acr("CAD")‑Methoden vor allem geometrische Darstellungen liefern, versteht sich #acr("BIM") als integraler Informations‑, Koordinations‑ und Managementprozess über den gesamten Lebenszyklus eines Bauwerks hinweg. #cite(<eubimtg_handbuch_nodate>) betont dabei, dass #acr("BIM") nicht ausschließlich als Software oder 3D‑Modell, sondern als übergreifende Methode der strukturierten Informationsverwaltung verstanden werden muss, in der digitale Modelle sowohl grafische als auch nicht‑grafische Daten konsistent abbilden und austauschbar machen. Im Kern verfolgt #acr("BIM") das Ziel, Daten durchgängig, koordiniert und transparent bereitzustellen, sodass Planungs‑, Ausführungs‑ und Betriebsprozesse effizienter, verlässlicher und qualitativ hochwertiger gestaltet werden können. #cite(<oebbecke_nachhaltigkeit_2025>)

Die Prinzipien von #acr("BIM") basieren auf standardisierten Datenstrukturen, klar definierten Informationsanforderungen und interoperablen Austauschformaten. Offene Standards spielen dabei eine zentrale Rolle, insbesondere das #acr("IFC")‑Format, das als international anerkannter, herstellerneutraler Standard den modellbasierten Datentransfer ermöglicht. #cite(<eubimtg_handbuch_nodate>) beschreibt #acr("IFC") als ein wesentliches Element für die softwareunabhängige Datenübergabe und betont, dass nur durch offene Formate die langfristige Nutzbarkeit und Kompatibilität von Projektinformationen gewährleistet werden kann. Ergänzt wird #acr("IFC") durch organisatorische Standards wie die internationale Normenreihe ISO 19650 #cite(<iso_iso_2018>), die grundlegende Anforderungen an Verantwortlichkeiten, Prozesse, Datenstrukturen und Informationsflüsse definiert. Diese Normen schaffen Klarheit über die Art, Tiefe und Qualität der Daten, die innerhalb eines #acr("BIM")‑Projekts erzeugt und ausgetauscht werden müssen. Auch #cite(<golinski_bim-magazin_2025>) verdeutlicht, dass die zunehmende Standardisierung, sowohl technisch als auch organisatorisch, eine der wichtigsten Voraussetzungen für den breiten und konsistenten Einsatz der Methode ist, da sie Missverständnisse reduziert und modellbasierte Prozesse in einheitliche Strukturen überführt. #cite(<oebbecke_nachhaltigkeit_2025>) #cite(<fouad_lehrbuch_2013>)

Der Nutzen von #acr("BIM") erstreckt sich über sämtliche Phasen eines Bauwerks und zeigt sich besonders deutlich durch die Verknüpfung von Planung, Ausführung und Betrieb. In der Planungsphase unterstützt #acr("BIM") die Entwicklung hochpräziser und semantisch angereicherter digitaler Modelle, die sowohl geometrische Informationen als auch Materialeigenschaften, technische Daten oder Wartungsanforderungen enthalten. Das digitale Modell dient damit als zentrale Informationsquelle, wodurch Fachplaner frühzeitig gemeinsame Entscheidungen treffen und Konflikte vermeiden können. Simulationen, automatisierte Auswertungen und modellbasierte Koordinationsprozesse verbessern die Qualität der Planung erheblich und ermöglichen Entscheidungen auf Basis belastbarer digitaler Analysen. Das #acr("BIM")‑Magazin zeigt anschaulich, dass modellbasierte Prozesse die Transparenz erhöhen, Projektbeteiligte enger zusammenführen und die Verständlichkeit technischer Sachverhalte verbessern, da das Modell selbst zum zentralen Kommunikationsmedium wird. #cite(<fouad_lehrbuch_2013>)

Während der Ausführung ermöglicht #acr("BIM") eine präzisere Steuerung der Bauabläufe, eine zuverlässige Terminplanung sowie eine modellgestützte Qualitätssicherung. Durch die Verknüpfung von Modellen und Bauprozessen lassen sich Baustellenlogistik, Ressourcenplanung oder Mängelmanagement digital und nachvollziehbar abbilden. Zudem sinkt die Anzahl der Planungsfehler, da modellbasierte Abläufe auf konsistenten Daten basieren und Änderungen automatisch im Modell sichtbar werden. Auch in dieser Phase trägt #acr("BIM") zu einer geringeren Fehleranfälligkeit und einem effizienteren Informationsfluss bei. #cite(<oebbecke_nachhaltigkeit_2025>), #cite(<fouad_lehrbuch_2013>)

Im Betrieb entfaltet #acr("BIM") schließlich seinen langfristigen Mehrwert: Das digitale Modell fungiert als zentraler Datenspeicher für alle relevanten Informationen eines Bauwerks. Betreiber können auf hinterlegte Wartungszyklen, Bauteilinformationen oder technische Dokumentationen zugreifen, ohne auf verschiedene Dokumentquellen angewiesen zu sein. Dadurch wird nicht nur die Bewirtschaftung effizienter, sondern auch der Lebenszyklus des Gebäudes besser steuerbar. #cite(<eubimtg_handbuch_nodate>) verweist darauf, dass strukturierte und konsistente Daten die Grundlage für ein modernes, datenbasiertes Facility Management bilden und zukünftige Optimierungen, Umbauten oder Erweiterungen wesentlich erleichtern. #cite(<oebbecke_nachhaltigkeit_2025>)

Insgesamt zeigt sich, dass #acr("BIM") weit mehr ist als eine technische Methode. Es handelt sich um ein umfassendes Konzept für die digitale Transformation des Bauwesens, das auf klaren Standards, einheitlichen Datenstrukturen und der kollaborativen Nutzung digitaler Modelle basiert. Der Nutzen erstreckt sich über alle Projektphasen hinweg und führt zu effizienteren, transparenteren und nachhaltigeren Planungs‑ und Betriebsprozessen.


== Digitaler Zwilling

Der digitale Zwilling entwickelt sich zunehmend zu einem zentralen Baustein digitaler Transformationsprozesse in technischen Systemen, Bauwerken und Infrastrukturen. Er beschreibt ein virtuelles Abbild eines realen Assets, das nicht nur dessen physische Eigenschaften, sondern auch dessen funktionale, betriebliche und zeitliche Dimensionen modelliert. Im Gegensatz zu statischen Modellen handelt es sich beim digitalen Zwilling um ein dynamisches, kontinuierlich aktualisiertes Datenobjekt, das im Laufe des gesamten Lebenszyklus eines Systems mitwächst. #cite(<golinski_bim-magazin_2025>, supplement: "p. 15") beschreibt den digitalen Zwilling als „kontinuierlich aktualisiertes, semantisch strukturiertes Modell“, das über Echtzeitinformationen aus verschiedensten Datenquellen gespeist wird und damit eine datenbasierte Grundlage für ein vorausschauendes Infrastruktur‑ und Anlagenmanagement bildet.

=== Konzept und Architektur

Das Konzept des digitalen Zwillings basiert auf der engen Kopplung zwischen realem Objekt und digitalem Modell. Dabei wird eine strukturierte, domänenübergreifende Systemarchitektur aufgebaut, die geometrische, technische, semantische und prozessuale Informationen miteinander verknüpft. Grundlage ist dabei ein integriertes Datenmodell, dessen Struktur sowohl die physische Komplexität eines Assets als auch seine funktionalen und betrieblichen Eigenschaften abbildet. In der Datei Digital Twins, Simulation, and the Metaverse wird hervorgehoben, dass die Architektur eines digitalen Zwillings auf einer einheitlichen Datenbasis („single source of truth #cite(<grieves_digital_2024>, supplement: "p. 347")“) aufbaut, die über APIs mit verschiedenen externen Systemen vernetzt und durch integrierte Datenanalysewerkzeuge fortlaufend erweitert wird. Diese Architektur ermöglicht eine multidisziplinäre Nutzung des Modells und verhindert Informationsverluste über System‑ und Organisationsgrenzen hinweg.

Der digitale Zwilling bildet damit ein hochstrukturiertes, hierarchisches Informationssystem, in dem Daten in geschichteten Ebenen organisiert werden. Für die Energiewirtschaft beschreibt #cite(<schwab_elektroenergiesysteme_2022>), dass digitale Zwillinge als „hochgranulare mathematische Modelle“ realer Anlagen dienen, die zunächst mit Projektparametern aufgebaut und später mit Echtzeit‑Betriebsdaten angereichert werden. Dadurch lassen sich sogar risikoreiche oder zerstörerische Prozesszustände virtuell untersuchen, ohne reale Anlagen zu gefährden.

=== Datenintegration und Echtzeit‑Updates

Eine wesentliche Eigenschaft des digitalen Zwillings ist die permanente Synchronisation zwischen den realen und virtuellen Systemzuständen. Digitale Zwillinge verwenden hierfür Datenströme aus Sensorik, Automatisierungstechnik, #acr("IoT") Plattformen und Betriebsleitsystemen, um das Modell laufend zu aktualisieren. #cite(<golinski_bim-magazin_2025>) beschreibt, dass Echtzeitdaten die Modelle kontinuierlich präzisieren und damit eine laufende Optimierung von Betrieb, Überwachung und Wartung ermöglichen. Insbesondere im Bau‑ und Gebäudemanagement führt diese enge Datenkopplung zu einer verlängerten Lebensdauer, besseren Betriebsabläufen und deutlich geringeren Betriebskosten.

Auch in industriellen Anwendungen spielt die Echtzeitintegration eine entscheidende Rolle. In #cite(<grieves_digital_2024>) wird erläutert, dass digitale Zwillinge auf skalierbaren Dateninfrastrukturen aufbauen, die den Zugriff auf kuratierte und gesicherte Daten ermöglichen. Über standardisierte Schnittstellen können externe Datenquellen integriert werden, wodurch ein stetig wachsender und sich selbst verbessernder Datenpool entsteht, der tiefgehende Analysen, Simulationen und Prognosen erlaubt.

Diese dynamische Verbindung zwischen Modell und Realität bildet das Fundament für eine Vielzahl datengetriebener Prozesse. Diese reichen nach #cite(<schwab_elektroenergiesysteme_2022>) von der automatisierten Modellvalidierung über Predictive Maintenance bis zur Simulation zukünftiger Systemzustände in kritischen Energie‑ und Produktionsanlagen.

=== Anwendungsfälle

Die Einsatzmöglichkeiten digitaler Zwillinge sind vielseitig und erstrecken sich über zahlreiche Branchen. Im Infrastrukturbereich dienen digitale Zwillinge der vorausschauenden Steuerung, Fehleranalyse und Optimierung technischer Bauwerke. #cite(<golinski_bim-magazin_2025>) zeigt anhand des Masterplans „Digitaler Zwilling Bundesfernstraßen #cite(<meister_masterplan_2021>)“, wie digitale Modelle für ein integriertes, datenbasiertes Management komplexer Infrastruktursysteme genutzt werden sollen.

Ein besonders relevanter Anwendungsbereich ist die Energiebranche. Digitale Zwillinge ermöglichen die Simulation extremer Betriebszustände, die Analyse von Netzsituationen und die Optimierung von Anlagenverfügbarkeit. #cite(<schwab_elektroenergiesysteme_2022>) beschreibt, dass digitale Zwillinge in Kraftwerken oder Schaltanlagen zur Nachbildung realer Prozesse verwendet werden, um Risiken frühzeitig zu erkennen, die Betriebssicherheit zu erhöhen und die Verfügbarkeit zu maximieren. Das virtuelle Modell dient dabei nicht nur der Überwachung, sondern auch der Ausbildung, Szenariosimulation und Entscheidungsunterstützung im laufenden Betrieb.

Hinzu kommen moderne Anwendungen im Bereich Hochspannungs‑ und Gleichstromtechnik: #cite(<adhya_identiq_2025>) zeigt, wie digitale Zwillinge speziell für HVDC‑Systeme genutzt werden können, um komplexe Betriebsdaten zu analysieren, Anlagenzustände zu visualisieren und Schnittstellen zwischen verschiedenen technischen Disziplinen zu harmonisieren. Die Plattform unterstützt Betreiber dabei, Fehlerursachen schneller zu identifizieren, Wartungsmaßnahmen zu optimieren und die gesamte Lebensdauer kritischer Energiesysteme digital abzubilden.

Darüber hinaus eröffnen digitale Zwillinge neue Potenziale im Bereich Nachhaltigkeit und Ressourceneffizienz. Sie ermöglichen die präzise Prognose von Energieverbräuchen, verringern Materialüberschüsse, unterstützen emissionsoptimierte Betriebsstrategien und schaffen fundierte Entscheidungsgrundlagen für Umbauten oder Nachrüstungen. In der Architektur und Stadtplanung werden digitale Zwillinge genutzt, um ökologische, technische und soziale Parameter zu simulieren und dadurch resilientere und effizientere Bauwerke zu entwickeln, wie #cite(<oebbecke_nachhaltigkeit_2025>) beschreibt.