#import "@local/templat-projektarbeit:0.1.15": *
#import "../../Zusatz/acronyms.typ": acronyms

= Herausforderungen und Chancen

#acr("BIM") und der Digitale Zwilling markieren zentrale Meilensteine auf dem Weg zur Digitalisierung im Bauwesen. Beide Methoden eröffnen die Möglichkeit, komplexe Informationen strukturiert zu erfassen, zu analysieren und über den gesamten Lebenszyklus eines Bauwerks verfügbar zu machen. Während #acr("BIM") vor allem die Planung und Errichtung unterstützt, erweitern Digitale Zwillinge das Konzept durch Echtzeitdaten, sensorische Rückkopplung und prädiktive Funktionen – insbesondere im Betrieb. Diese Entwicklungen sind sowohl mit erheblichen Potenzialen als auch mit technischen und organisatorischen Herausforderungen verbunden.

== Technische Herausforderungen

Eine der grundlegenden technischen Herausforderungen ergibt sich aus der Heterogenität der Daten sowie der schwer zu gewährleistenden Interoperabilität zwischen Systemen und Softwarelösungen. Wie im #cite(<golinski_bim-magazin_2025>) beschrieben, bestehen vielfach fehlende Standards, unzureichende Austauschformate und stark divergierende Software-Ökosysteme, was den nahtlosen Informationsfluss beeinträchtigt. Die Umfrageergebnisse weisen auf Probleme wie „fehlende Interoperabilität“, „Software‑Zoo“ und „unzureichende #acr("IFC")‑Konformität“ hin, die zu Mehraufwand und Fehleranfälligkeit führen.

Auch die technische Komplexität im Zusammenhang mit Digitalen Zwillingen ist erheblich. Je nach Anwendungsfall können digitale Modelle unterschiedlich große räumliche Ausdehnungen umfassen. Modelle können von wenigen Bauteilen bis hin zu kompletten Infrastrukturnetzen reichen. Mit wachsendem Umfang steigen Datenvolumen und Anforderungen an Kommunikations‑, Integrations- und Auswertungstechnik. Der Aufbau eines Digitalen Zwillings verlangt daher eine klare Festlegung des #acr("LOIN"), einschließlich Geometrie, Semantik und Dokumentation. Außerdem bringt die Kopplung mit Echtzeitdaten, durch eingebettete Sensorik, zusätzliche Herausforderungen mit sich. Kontinuierliche Datenströme müssen verarbeitet, bewertet und in das Modell integriert werden, wobei sowohl Datenqualität als auch Verlässlichkeit sicherzustellen sind. Besonders in sicherheitskritischen Bereichen wie Tunnelüberwachung darf der Mensch weiterhin eingebunden bleiben, was hybride Entscheidungsprozesse erforderlich macht. #cite(<fazekas_digitaler_2024>)

Ein weiteres technisches Hindernis liegt im Datenmanagement. Die Anforderungen an Klassifikation, Versionierung, Metadatenverwaltung, Zugriffsrechte und Archivierungsprozesse sind hoch. Damit Informationen verlässlich genutzt werden können, bedarf es klar definierter Regeln für Datenstrukturierung, Metadaten, Prüfprozesse und Workflows innerhalb einer #acr("CDE"). #cite(<meister_masterplan_2021>)

Der Einsatz von #acr("KI") gestützten Analyse‑ und Vernetzungswerkzeugen bietet zwar Chancen, erhöht jedoch zugleich die Komplexität: Die Integration von #acr("KI") setzt saubere Daten, standardisierte Schnittstellen und hohe Rechnerkapazitäten voraus. Nur mit einheitlichen Datenformaten und interoperablen Systemen können die Potenziale digitaler Technologien ausgeschöpft werden.

== Organisatorische Aspekte

Neben den technischen Hürden stellen organisatorische Rahmenbedingungen einen wesentlichen Hemmschwelle dar. #cite(<golinski_bim-magazin_2025>) beschreibt eine Vielzahl an Hindernissen, die den organisatorischen Wandel erschweren: fehlende personelle Kapazitäten, mangelndes Know-how, unzureichende Schulungen, zusätzliche Abstimmungsaufwände und hohe Implementierungskosten. Ebenso werden Widerstände durch alte Arbeitskulturen sowie fehlendes oder widersprüchliches Verständnis zentraler Begriffe genannt. Auch auf System‑ und Governance‑Ebene werden organisatorische Defizite sichtbar. In Deutschland etwa sind Zuständigkeiten im Bauwesen stark dezentral. Unterschiedliche Regelwerke, Anforderungen und fragmentierte Prozesse erschweren die durchgängig digitale Zusammenarbeit. Fortschritte werden nur möglich, wenn Akteure ressortübergreifend kooperieren und Pilotprojekte vorantreiben.

Im Datenmanagement zeigt sich ebenfalls großer organisatorischer Aufwand: Der Aufbau einer gemeinsamen Datenumgebung verlangt klare Definitionen zu Prozessen, Verantwortlichkeiten, Datenschutz, Nutzungsrechten und Sicherheitsmaßnahmen. Alle Beteiligten müssen in der Anwendung geschult, Standards müssen verbindlich festgelegt und kontrolliert werden. Die erfolgreiche Nutzung einer #acr("CDE") hängt stark vom Einhalten gemeinsamer Regeln, Akzeptanz und konsequentem organisatorischem Mittragen ab. #cite(<meister_masterplan_2021>)

Darüber hinaus wird im digitalen Zwilling ein kontinuierliches Organisations- und Datenpflegekonzept erforderlich. Die regelmäßige Aktualisierung von Daten, Integration neuer Quellen und Sicherstellung der Datenqualität erfordern langfristig Ressourcen, Rollen und klare Zuständigkeiten. Ohne diese organisatorische Kontinuität verliert der Digitale Zwilling schnell seine Aktualität und damit seinen Mehrwert. #cite(<fazekas_digitaler_2024>)

Auf europäischer Ebene weisen #cite(<eubimtg_position_2025>) darauf hin, dass fehlende Harmonisierung der #acr("BIM")‑Regelungen zwischen Mitgliedstaaten organisatorische Barrieren für Kooperation, Ausschreibung und die Entwicklung internationaler Standards darstellt. Eine europaweit abgestimmte Linie könnte die Fragmentierung verringern und gemeinsame Prozesse fördern.

== Chancen
Trotz der vielfältigen Herausforderungen bieten #acr("BIM") und insbesondere Digitale Zwillinge enorme Chancen, die das Bauwesen langfristig transformieren können. Die im #cite(<golinski_bim-magazin_2025>) zusammengetragenen Vorteile zeigen ein breites Spektrum: effizientere Planung, höhere Datenqualität, Kollisionsprüfungen, Transparenz, bessere Kommunikation, reduzierte Fehler und Bauverzögerungen sowie die Möglichkeit, Lebenszyklusinformationen konsistent zu nutzen. #acr("BIM") wird als Fundament einer durchgängigen digitalen Wertschöpfungskette verstanden.

Der Digitale Zwilling erweitert diese Potenziale erheblich. Durch die Integration von Echtzeitdaten entsteht eine dynamische und lernfähige virtuelle Repräsentation, die über den gesamten Lebenszyklus zum Einsatz kommt. Betreiber profitieren von automatisierten Analysen, besseren Prognosen und prädiktiven Wartungsstrategien. Dies führt zu längeren Nutzungsdauern, höherer Verfügbarkeit und ressourcenschonenderen Betriebsprozessen. Die Wirtschaft profitiert ebenfalls: Die erhöhte Datenverfügbarkeit ermöglicht neue Geschäftsmodelle, effizientere Abläufe und Innovationen. Forschungseinrichtungen erhalten Zugriff auf Testfelder und Daten, wodurch neue Methoden schneller in die Anwendung überführt werden können. Auch gesellschaftlich entstehen Vorteile: verbesserte Mobilität, höhere Sicherheit, reduzierte Reisezeiten und ein Beitrag zu Klimazielen durch optimierte Ressourcennutzung sowohl in Infrastruktur als auch im Hochbau. #cite(<fazekas_digitaler_2024>)

In planerischer Hinsicht eröffnet #acr("BIM") in Verbindung mit #acr("KI") und Simulation eine neue Qualität der Entscheidungsunterstützung. Simulationswerkzeuge, die auf #acr("BIM")‑Modellen aufbauen, ermöglichen präzisere Vorhersagen, bessere Energieeffizienz, optimierte Bauabläufe und nachhaltigere Gestaltung. #cite(<oebbecke_nachhaltigkeit_2025>)

Nicht zuletzt ermöglicht eine harmonisierte #acr("BIM")‑Strategie eine effizientere öffentliche Beschaffung, höhere Transparenz, bessere Nachhaltigkeit und wirtschaftliche Vorteile für die gesamte Wertschöpfungskette.