#import "@local/templat-projektarbeit:0.1.15": *
#import "../../Zusatz/acronyms.typ": acronyms

= Theoretical Background

This chapter establishes the theoretical basis required for the subsequent validation and quality assessment of current-transformer calculations in SECP Global. It introduces the operating principles and relevant characteristics of #acrfpl("CT"), explains their use in transformer differential and overcurrent protection, identifies the applicable parts of the #acr("IEC") 61869 series and defines the #acr("CT") performance parameters used in protection-oriented dimensioning and verification. 

== #acrl("CT")

A #acr("CT") is an instrument transformer in which the secondary current is substantially proportional to the primary current under normal operating conditions. For the appropriate direction of connection, the phase displacement between the primary and secondary currents is approximately zero. A protective current transformer is specifically intended to transmit a current information signal to protection and control devices. #cite(<international_electrotechnical_commission_iec_2012>)

In practical power-system applications, a #acr("CT") converts a comparatively high primary current $I_p$​ into a lower secondary current $I_s$ Is​ that can be supplied to measuring instruments or protective devices. The transformation is determined primarily by the ratio between the primary and secondary turns. Further relevant characteristics include the rated primary and secondary currents, accuracy class, accuracy limit factor, excitation characteristic, secondary winding resistance and rated burden. #cite(<mustajarvi_instrument_2016>)

The simplified equivalent circuit of a conventional #acr("CT") contains the secondary winding resistance $R_"ct"$, the connected burden and a magnetising branch representing the magnetic behavior of the core. Part of the transformed current is required as excitation current. Consequently, the actual secondary current does not reproduce the primary current perfectly. This produces a current ratio error and a phase displacement between the primary current referred to the secondary side and the actual secondary current. #cite(<mustajarvi_instrument_2016>), #cite(<abb_power_distribution_instrument_nodate>)

#cite(<international_electrotechnical_commission_iec_2012>) distinguishes between measuring and protective current transformers. A measuring #acr("CT") transmits a current signal to measuring instruments and meters, whereas a protective #acr("CT") supplies protection and control devices. The required behavior differs accordingly. Measuring cores are intended to provide suitable accuracy within their specified measuring range. Protective cores must retain sufficient current reproduction at the substantially higher currents that can occur during system faults.  #cite(<mustajarvi_instrument_2016>)

For protection purposes, the magnetic behavior of the #acr("CT") core is particularly important. As the secondary electromotive force and the corresponding magnetic flux increase, the core approaches saturation. In this condition, an increasing part of the primary current is required for magnetisation and the secondary current can become distorted and deficient. Saturation can therefore impair the current signal supplied to the protection device and may contribute either to a failure to operate or to unwanted operation, depending on the protection principle and fault condition. #cite(<international_electrotechnical_commission_iec_2017-2>), #cite(<mustajarvi_instrument_2016>)

CT performance during a fault is not determined by primary current alone. The required secondary electromotive force also depends on the #acr("CT") ratio, the secondary winding resistance, the impedance of the secondary leads and the connected device burden. The burden is the impedance connected to the #acr("CT") secondary circuit and includes the connected protection device and the secondary wiring. Cable length, conductor cross-section, conductor material and temperature influence the cable resistance and therefore the total secondary burden. #cite(<mustajarvi_instrument_2016>), #cite(<abb_power_distribution_instrument_nodate>)

The rated secondary current is one of the principal #acr("CT") ratings. #cite(<international_electrotechnical_commission_iec_2012>) specifies standard rated secondary currents of 1A and 5A. For protective current transformers intended for specified transient performance, the standard rated secondary current is 1A. #cite(<international_electrotechnical_commission_iec_2012>) also defines rated short-time thermal current and rated dynamic current as separate withstand quantities. These ratings concern thermal and mechanical withstand capability and are therefore distinct from the accuracy and saturation parameters used to assess measurement performance.

The #acr("CT") secondary circuit must not be opened while primary current is present. An open secondary circuit removes the normal secondary current path, so the primary current acts predominantly as magnetising current. The resulting flux and secondary voltage can become very high, creating a hazard to personnel and potentially damaging the #acr("CT") insulation or connected equipment. #cite(<karthik_transformer_2025>), #cite(<mustajarvi_instrument_2016>)

== Protection Applications

Protection devices use the secondary signals supplied by instrument transformers to detect abnormal power-system conditions. Different protection functions process these signals according to different operating principles and therefore impose different requirements on the associated CTs. The relevant #acr("CT") specification must consequently be related to the particular protection function rather than derived from the primary current rating alone. #cite(<international_electrotechnical_commission_iec_2017-2>), #cite(<mustajarvi_instrument_2016>)


=== Transformer Differential Protection

Differential protection compares the currents entering and leaving a defined protection zone. Under normal load and external-fault conditions, the vector sum of the correctly referred currents should ideally be zero. An internal fault produces a differential current that indicates a fault within the protected zone. In transformer differential protection, the compared currents are measured by CTs installed on the different sides of the power transformer. #cite(<international_electrotechnical_commission_iec_2017-2>), #cite(<hitachi_energy_ref650_2026>)

A direct comparison of the measured currents requires compensation for the transformation properties of the protected power transformer. The relevant factors include the phase shift associated with the transformer vector group, the difference between #acr("CT") secondary-current magnitudes on the different transformer sides and zero-sequence current. In numerical protection devices, these corrections can be implemented in software using the entered #acr("CT") and power-transformer rated data. #cite(<karthik_transformer_2025>), #cite(<hitachi_energy_ref650_2026>)

If the transformation ratio and phase shift are correctly compensated, the differential current should theoretically be zero during normal load and external faults. In practice, non-fault phenomena can produce an apparent differential current. The RET670 application manual identifies tap-changer-related mismatch, differences in #acr("CT") characteristics and operating conditions, zero-sequence current present on only one side of the transformer, normal magnetising current, magnetising inrush current and overexcitation current as possible causes. #cite(<karthik_transformer_2025>)

Transformer differential protection must simultaneously provide sensitivity to internal faults and stability during external faults. Restrained differential protection uses a bias or restraint quantity so that the required operating current increases with the current passing through the transformer. This proportional restraint supports stability during through faults while retaining sensitivity at lower bias currents. The RET670 and REF650 documentation describes the highest measured transformer current as the bias quantity used by the respective differential function. #cite(<karthik_transformer_2025>), #cite(<hitachi_energy_ref650_2026>)

CT saturation is a particularly important consideration in differential protection. If CTs on the different sides of the protected transformer saturate unequally, their secondary currents no longer correspond even though the primary fault is outside the protected zone. The resulting current difference can appear to the relay as a false differential current. The second and third sections of the restrained operating characteristic therefore provide increased restraint under heavy through-fault conditions, during which #acr("CT") saturation and transformer losses can increase the measured differential current. #cite(<karthik_transformer_2025>), #cite(<international_electrotechnical_commission_iec_2017-2>)

Both internal and external faults must be considered when specifying the CTs for transformer differential protection. #cite(<international_electrotechnical_commission_iec_2017-2>) identifies the external fault as typically the most critical condition for differential protection because stability must be maintained despite high through-fault currents. The report also notes that a severe internal fault can produce #acr("CT") saturation, particularly where the fault is located between the high-voltage #acr("CT") and the transformer and the source impedance is low.

The #acr("CT") ratio must be adapted to the nominal current of the protected transformer. #cite(<international_electrotechnical_commission_iec_2017-2>) recommends correct CT-core dimensioning based on the relevant fault occurrences and identifies anti-remanence classes such as 5PR, TPY, TPZ and PXR as applicable options for transformer differential protection. The specific project requirement must nevertheless be determined from the relevant protection-device documentation and the actual power-system conditions. 

=== Overcurrent Protection

Overcurrent protection operates when the measured current exceeds a defined pickup value. The available operating characteristics include instantaneous, definite-time and inverse-time-delayed protection. Instantaneous protection operates when the pickup current is exceeded without an intentional time delay. Definite-time protection operates after the current has remained above the pickup level for the specified delay. For inverse-time protection, the operating time decreases as the measured current increases. #cite(<mustajarvi_instrument_2016>)

The ratio error of a #acr("CT") is particularly relevant to overcurrent protection because the protection decision is based directly on the measured current magnitude. Directional overcurrent protection additionally depends on phase relationships and is therefore also affected by #acr("CT") phase displacement. #cite(<international_electrotechnical_commission_iec_2012>) states that the combination of ratio error and phase displacement is represented by the composite error.

CT requirements for overcurrent protection depend on the applied operating characteristic. #cite(<international_electrotechnical_commission_iec_2017-2>) presents separate application recommendations for non-directional and directional overcurrent functions. For definite stages, the accuracy limit factor must exceed the maximum current setting. For inverse stages, the report gives an ALF requirement greater than 20 while considering the actual fault currents. It identifies class 10P for non-directional overcurrent protection and class 10P or potentially 5P, for directional protection. 

The overcurrent application must therefore be defined before #acr("CT") adequacy is evaluated. The source material distinguishes between directional overcurrent, non-directional instantaneous or definite-time overcurrent and non-directional inverse-time overcurrent because the associated required secondary electromotive-force conditions are not identical. The maximum close-in fault current, primary pickup current, #acr("CT") ratio, secondary winding resistance, device burden and lead resistance are among the quantities used in the corresponding assessment. #cite(<mustajarvi_instrument_2016>)

Selectivity is an additional consideration for time-delayed overcurrent protection. In a radial system, the operating times of successive protection devices are coordinated so that the protection closest to the fault can clear it while upstream protection remains available as delayed backup. The selected time difference must account for protection operating time, circuit-breaker opening time, protection reset time and an appropriate safety margin. #cite(<karthik_transformer_2025>)

== Relevant Standards

The #acr("IEC") 61869 series provides the principal standards framework for instrument transformers within the supplied source material. #cite(<international_electrotechnical_commission_iec_2023>) specifies general requirements for instrument transformers. Its scope includes ratings, environmental conditions, dielectric requirements, output ratings, accuracy requirements, design and construction, testing, installation, operation, maintenance and safety.

#cite(<international_electrotechnical_commission_iec_2012>) specifies additional requirements for current transformers. It defines current-transformer terminology, rated currents, output values, protective and measuring accuracy classes, short-time current ratings, terminal markings, rating-plate information and the applicable type, routine and special tests. It also defines the protective classes P, PR, PX, PXR, TPX, TPY and TPZ. 

#cite(<international_electrotechnical_commission_iec_2017-2>) provides guidance for applying current transformers in power-system protection. Its contents address the basic electrical model, transient behaviour, duty cycles, transient dimensioning, core saturation, remanence, relationships between #acr("CT") classes and the specification of CTs for individual protection functions. The protection applications covered include overcurrent, distance, transformer differential, busbar differential, line differential and high-impedance differential protection.

The three documents have complementary functions in the context of this thesis. #cite(<international_electrotechnical_commission_iec_2023>) supplies the general instrument-transformer requirements, #cite(<international_electrotechnical_commission_iec_2012>) supplies the CT-specific definitions and requirements and #cite(<international_electrotechnical_commission_iec_2017-2>) relates #acr("CT") behaviour and dimensioning parameters to protection applications. These documents therefore provide the standards basis against which the CT-related terminology, parameters and calculation logic of SECP Global can be assessed.

== #acr("CT") Performance Parameters

The rated primary current $I_"pr"$​ is the primary-current value on which #acr("CT") performance is based. The rated secondary current $I_"sr"$​ is the corresponding basis for secondary performance. Together, these quantities define the rated current transformation ratio used to refer the primary current to the secondary side. #cite(<international_electrotechnical_commission_iec_2012>)

The secondary winding resistance $R_"ct"$​ is the resistance of the #acr("CT") secondary winding. It contributes to the voltage that must be induced internally to drive the required secondary current. For a given secondary current, a larger winding resistance increases the required secondary electromotive force. #cite(<international_electrotechnical_commission_iec_2012>) treats $R_"ct"$​ as an actual #acr("CT") quantity and distinguishes it from a specified upper limit.

The burden represents the impedance connected to the #acr("CT") secondary circuit. It includes the protection-device input and the connecting leads. Since the burden determines part of the voltage that the #acr("CT") must provide, #acr("CT") accuracy and saturation performance must be considered at the applicable burden rather than independently of the connected circuit. #cite(<international_electrotechnical_commission_iec_2012>), #cite(<mustajarvi_instrument_2016>), #cite(<abb_power_distribution_instrument_nodate>)

The rated output $S_n$​ is expressed in volt-amperes for measuring CTs and for classes P and PR. #cite(<international_electrotechnical_commission_iec_2012>) specifies standard rated-output values of 2.5, 5, 10, 15 and 30 VA, while values above 30 VA may be selected where required by the application. For classes TPX, TPY and TPZ, the standard specifies rated resistive burden values in ohms.

The accuracy class defines the applicable limits of #acr("CT") error. For classes P and PR, the class designation is associated with limits for ratio error, phase displacement and composite error. The composite error cannot be smaller than the vector combination of ratio error and phase displacement. For overcurrent relays, ratio error is particularly relevant; for phase-sensitive functions, phase displacement is also significant; and for differential protection, the combined errors of the participating CTs must be considered. #cite(<international_electrotechnical_commission_iec_2012>)

The accuracy limit factor $K_"ALF"$, commonly abbreviated as ALF, is the ratio between the rated accuracy-limit primary current $I_"ALF"$ and the rated primary current:

$ K_"ALF" = I_"ALF" / I_"pr" $

$ I_"ALF" = K_"ALF" * I_"pr" $

The rated accuracy-limit primary current is the primary-current value up to which the #acr("CT") complies with the applicable composite-error requirements. #cite(<international_electrotechnical_commission_iec_2012>)

The knee-point electromotive force is relevant particularly to classes PX and PXR. #cite(<international_electrotechnical_commission_iec_2012>) identifies it as the lower limit of the knee-point e.m.f. and relates it to the dimensioning factor $K_x$, secondary winding resistance, rated burden resistance and rated secondary current:

$ E_k = K_x (R_"ct" + R_b) I_"sr" $

For PX and PXR CTs, the excitation characteristic, secondary winding resistance, burden resistance and turns ratio provide the information required to assess performance in relation to the associated protection system. #cite(<international_electrotechnical_commission_iec_2012>)

Saturation denotes the operating region in which the #acr("CT") core can no longer reproduce increasing primary current proportionally at the secondary terminals. Fault-current asymmetry and its decaying direct-current component can increase the magnetic flux beyond that produced by the symmetrical alternating component alone. #cite(<international_electrotechnical_commission_iec_2017-2>) therefore uses the time to accuracy limit, the transient factor and the transient dimensioning factor to describe and determine the required transient #acr("CT") performance.

Remanence is the magnetic flux that remains in the #acr("CT") core after the magnetising excitation has been removed. Because existing remanent flux reduces the remaining flux margin in one direction, it can lead to earlier saturation during a subsequent fault. #cite(<international_electrotechnical_commission_iec_2012>) differentiates classes with and without a specified remanent-flux limit. Classes PR, PXR and TPY include a remanence limit, whereas classes P, PX and TPX do not. Class TPZ is specified through a secondary time constant and the alternating component of the instantaneous error. #cite(<international_electrotechnical_commission_iec_2017-2>)

The #acr("CT") classes consequently represent different methods of specifying protection performance. Classes P and PR are defined through composite-error requirements under symmetrical steady-state short-circuit conditions. Classes PX and PXR are specified through the excitation characteristic and associated circuit parameters. Classes TPX, TPY and TPZ are defined in relation to transient error under asymmetrical short-circuit conditions. Selection among these classes must therefore follow the protection principle, expected fault conditions, burden and applicable protection-device requirements. #cite(<international_electrotechnical_commission_iec_2017-2>), #cite(<international_electrotechnical_commission_iec_2012>)
